### ISSUE TITLE
Add an option for a `--dry-run` in our conformance test suite

### ISSUE THREAD

**Issue by tssurya** [kubernetes-sigs/network-policy-api#107]
See https://github.com/kubernetes-sigs/network-policy-api/pull/98#discussion_r1200840744 for details
/area conformance

**Comment by vpbh** [comment]
Hi @tssurya Can I take this one? Ive been observing the flow of conformance tests and I think I can get this done!

**Comment by npinaeva** [comment]
@tssurya do we even need this option? the original goal was AFAIU to run tests without the reference implementation https://github.com/kubernetes-sigs/network-policy-api/pull/98#discussion_r1200840744 which we do have now?

**Comment by tssurya** [comment]
@npinaeva that's right, the dry-run requirement came a time when we didn't have our own CI running e2es enough to know if the test interfaces were broken or not. I Believe given we have adopted kube-network-policy over the past year as the reference implementation and run our e2es now using that this shouldn't be needed... Can't think of other reasons we'd want the dry run..

**Comment by vpbh** [comment]
Thanks @npinaeva @tssurya!

**Comment by npinaeva** [comment]
Sorry we didn't catch it before you implemented this @vpbh !
It may be good to clarify the requirements on the issue just in case before implementing it, as some of them may be kinda old/ not well defined

**Comment by vpbh** [comment]
Thanks @npinaeva ! I will keep that in mind! I learnt a lot about conformance tests and the code flow! So no(t much) harm, no(t much) foul :)
