### ISSUE TITLE
Import legacy google doc use cases to this repo

### ISSUE THREAD

**Issue by abhiraut** [kubernetes-sigs/network-policy-api#12]

**Comment by astoycos** [comment]
I wonder what the best way to do this is... Just add the link to the older google documents or figure out some way to import them via markdown files?

**Comment by abhiraut** [comment]
yeah i added this issue to track the item; however i am unsure whether any of this material should be part of a repo. i dont see evidence of such in other repos. so i lean towards maintaining the link
