### ISSUE TITLE
Import NetworkPolicy recipes to this repo

### ISSUE THREAD

**Issue by abhiraut** [kubernetes-sigs/network-policy-api#13]
@ahmetb has a great collection of NetworkPolicy recipes at https://github.com/ahmetb/kubernetes-network-policy-recipes 
It would be nice to import these samples in to official network policy repository.

**Comment by kundan2707** [comment]
Should we import these sample to this repo?

**Comment by kundan2707** [comment]
I will restructure NetworkPolicy in repo as per comment recieved on #25
