### ISSUE TITLE
huntergregory as contributor to network-policy-api

### ISSUE THREAD

**Issue by huntergregory** [kubernetes-sigs/network-policy-api#167]
Interested in becoming a long-term contributor to network-policy-api.

EDIT: moving all details to https://github.com/kubernetes/org/issues/4573

**Comment by astoycos** [comment]
Hey Hunter, thanks for opening this :) 

The process of becoming a contributor isn't as simple as opening a PR against our repo and actually involves getting into K8s/org, you can find the instructions for doing so here -> https://github.com/kubernetes/community/blob/master/community-membership.md 

Before you open an issue I usually thing it's best to have spoken to your two sponsors beforehand, additionally make sure you mention (https://github.com/kubernetes-sigs/network-policy-api/pull/157) as well as the presentations + google docs you've completed/shared in our team meetings, you can even find the recordings on youtube if you want to link those as well!
