### ISSUE TITLE
[Policy Assistant] Predict Verdict and Flow of Decisions made by Policies

### ISSUE THREAD

**Issue by huntergregory** [kubernetes-sigs/network-policy-api#168]
Idea for #150.

Dependency: #152

Predict the effect of Policies on traffic, and visualize the relevant rules (from ANP, NetPol v1, and/or BANP) that produced the effect.

Prototype visualization:
![image](https://github.com/kubernetes-sigs/network-policy-api/assets/42728408/86511727-273a-4543-89c3-cd4fab797363)

**Comment by gabrielggg** [comment]
Hi @huntergregory can this be sumarized as: "Repurposing cyclonus analyze --mode=query-traffic" ?

**Comment by huntergregory** [comment]
Hey @gabrielggg, good call out. We're still in a stage of design iteration for this, and `query-traffic` mode may be a helpful reference for design or implementation. For reference, `query-traffic` mode looked like this for NetworkPolicyV1 ([full output](https://github.com/mattfenwick/cyclonus/blob/master/examples/cyclonus-output/analyze-query-traffic.txt)):
<img width="425" alt="image" src="https://github.com/kubernetes-sigs/network-policy-api/assets/42728408/5961b43f-56e4-400b-b733-02ebbdf554f7">

On the other hand, this is what we came up with for the KubeCon demo ([video](https://youtu.be/riSv0g-TNtI?si=VJLV5b9MJtsIZHJd&t=1234) and [code](https://github.com/huntergregory/network-policy-api/tree/kubecon/cmd/policy-assistant/kubecon)):
<img width="809" alt="image" src="https://github.com/kubernetes-sigs/network-policy-api/assets/42728408/c209ead6-66d2-471e-8e55-08381a35a9c5">

**Comment by gabrielggg** [comment]
hey @huntergregory awesome, first of all, congratulations on the great presentation on kubecon Paris, i just saw the video. At the end of the video, on the summary, you put a slide with the topics coming next on the project, and i saw that you highlighted this issue #168 , but seeing the demo and your previous screenshots i see that the walkthrough you proposed on this issue is almost done, so i just wanted to know how are you going to proceed with this issue, so that i can help.

**Comment by huntergregory** [comment]
Thanks @gabrielggg for the congrats and the interest, and sorry for the delay.

Just created #220, which is the main thing lacking right now. We could definitely use some help in this area! Feel free to assign yourself to that issue.

As for this issue (168), let me copy over the [KubeCon demo code](https://github.com/huntergregory/network-policy-api/tree/kubecon/cmd/policy-assistant/kubecon) to main branch as a starting point, but we can work on #220 independently of this.
