### ISSUE TITLE
[Policy Assistant] update binary names to policy-assistant instead of cyclonus

### ISSUE THREAD

**Issue by huntergregory** [kubernetes-sigs/network-policy-api#171]
Related to #150.

See https://github.com/kubernetes-sigs/network-policy-api/pull/159#discussion_r1375079221.

**Comment by Peac36** [comment]
Hey @huntergregory, should I also change the tag that is used during the building of the docker image?

**Comment by huntergregory** [comment]
Assuming the question's about image tags. I'd suggest we create a new docker image called `policy-assistant:v0.0.1`. We should probably establish a release process for creating new tags.

**Comment by Peac36** [comment]
What about the docker repo(`docker.io/mfenwick100`)? Should we continue to use that one or switch to k8s-related repo?

**Comment by huntergregory** [comment]
Ideally a k8s-related one. @astoycos do you know a repo we could use?
