### ISSUE TITLE
[CONFORMANCE] Use kube-network-policies to run conformance tests in the CI

### ISSUE THREAD

**Issue by tssurya** [kubernetes-sigs/network-policy-api#225]
**Why this is needed**:

We need to use https://github.com/kubernetes-sigs/kube-network-policies now that we have an implementation that will help us  catch CI flakes and improve our testing framework

thanks @aojea for the awesome work here. Definitely helps having a non-vendor implementation based CI runs that we can play with and maintain

TODO: Add a CI lane for this

**Comment by aojea** [comment]
It is already merged, isn't it ? 

https://github.com/kubernetes-sigs/network-policy-api/pull/224

**Comment by astoycos** [comment]
I think @tssurya  meant we should be running the core K8s network policy tests on the network-policy-api repo as well as in the core prow instance so that we can easily see if anything is broken/ go fix it

At the very least it'd be nice for us to be alerted if something was broken with the core tests so that we could assist in fixing them, since part of our charter is "maintaining the in-tree NetworkPolicy resource/tests"

**Comment by aojea** [comment]
you mean set a periodic job in prow?

**Comment by astoycos** [comment]
I was thinking run the core netpol tests against `kube-network-policies` in our github actions alongside the tests for ANP + BANP

But maybe Surya had something else in mind here?

**Comment by aojea** [comment]
kube-network-policies is used for kubernetes CI , periodic and presubmit

https://testgrid.k8s.io/sig-network-gce#network-policies,%20google-gce&width=20
https://testgrid.k8s.io/sig-network-gce#presubmit-network-policies,%20google-gce&width=20

There is a flake with one specific test , I'm investigating it here https://github.com/kubernetes-sigs/kube-network-policies/issues/12, but it seems some kernel or OS thing

 but there are zero flakes on the github actions in kube-network-policies

**Comment by aojea** [comment]
I don't fully understand but happy to help or discuss

**Comment by tssurya** [comment]
yes exactly what was done in https://github.com/kubernetes-sigs/network-policy-api/pull/224 except I didn't see that PR :) Andrew merged it too quick haha
my plan was to use kube-network-policies for running e2e's tests in this repo for presubmits.
