### ISSUE TITLE
[Policy Assistant] Cut the first release

### ISSUE THREAD

**Issue by huntergregory** [kubernetes-sigs/network-policy-api#255]
_EDIT: we are going to use `policy-assistant` instead of `pola` per #262_ 

Perhaps we can cut a release just for policy assistant, called v0.0.1-pola? Looks like there are no overlapping or bad connotations for this POLA abbreviation from my Google search 😅 

### Requirements

- CI/CD:
  - #170 
  - #254
  - #246
  - cut release
- features:
  - #245
  - #220

### Nice to have

- ~~#212~~:
  - added warning in #261
- ~~#151~~
  - removed unimplemented CLI args per #245

**Comment by huntergregory** [comment]
Discussed cutting a `v0.0.1-pola` release for the `pola` CLI in last week's meeting. We will target a release date of November 5th

**Comment by huntergregory** [comment]
Discussed tying pola version to the API version used. Discussed how the first release might not follow that format though.

Two ideas for first release:
- idea 1: `v0.0.1-pola`
- idea 2: `v0.1.1-pola-20241105`
  - `<api-version-used>-pola-<date>`

**Comment by npinaeva** [comment]
One question I have is do we plan to support multiple API versions with the same binary? It sounds like it could be useful to not reinstall the binary if you have 2 clusters with different ANP versions. In that case the tool could have its own versions, just adding support for newer API versions as it progresses?

**Comment by huntergregory** [comment]
> One question I have is do we plan to support multiple API versions with the same binary? It sounds like it could be useful to not reinstall the binary if you have 2 clusters with different ANP versions. In that case the tool could have its own versions, just adding support for newer API versions as it progresses?

After revisiting this question, I'm not sure we can support multiple API versions in the same CLI: https://stackoverflow.com/questions/63254746/how-to-import-two-versions-of-the-same-go-module

**Comment by huntergregory** [comment]
release complete: https://github.com/kubernetes-sigs/network-policy-api/releases/tag/v0.0.1-policy-assistant
