### ISSUE TITLE
Import Cyclonus into this repo 

### ISSUE THREAD

**Issue by astoycos** [kubernetes-sigs/network-policy-api#34]
If we want to look at using [Cyclonus](https://github.com/mattfenwick/cyclonus) for conformance testing I think we should move it upstream into this repo. 

I took a stab at this a while back https://github.com/kubernetes-sigs/network-policy-api/pull/29 but need someone to help push it forward.

**Comment by tssurya** [comment]
I can help with this!

**Comment by tssurya** [comment]
I have opened a new PR which is updated on current repo state: https://github.com/kubernetes-sigs/network-policy-api/pull/39 that should close this issue.

**Comment by tssurya** [comment]
PR has merged, closing this, we are ready to start with https://github.com/kubernetes-sigs/network-policy-api/issues/35
