### ISSUE TITLE
Add Gofmt and Govet gh actions 

### ISSUE THREAD

**Issue by astoycos** [kubernetes-sigs/network-policy-api#37]
Add GH actions to ensure the generated types have been created and gofmt has been run on any changes to the api itself (see the `make all` makefile target)

**Comment by astoycos** [comment]
@asim-reza are you going to have time for this? I would like to unassigned this to allow other folks to take it if not :)

**Comment by olivercodes** [comment]
I'll take it if it's open :)

**Comment by asim-reza** [comment]
Hey! Sorry got swamped with work... please feel free to take it @olivercodes ... 
/unassign
