### ISSUE TITLE
Update the AdminNetworkPolicy API KEP 

### ISSUE THREAD

**Issue by astoycos** [kubernetes-sigs/network-policy-api#42]
Update the KEP https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2091-admin-network-policy 

To be up to date with the API which actually merged.

Including, 
- BaselineAdminNetworkPolicy
- Selector changes 
etc

**Comment by astoycos** [comment]
@Dyanngg can you take care of this one if you get the chance?

**Comment by Dyanngg** [comment]
@astoycos will use https://github.com/Dyanngg/enhancements/pull/1 as a starting point.... This was never merged

**Comment by astoycos** [comment]
/remove-lifecycle stale 

This is on me to review :)

**Comment by astoycos** [comment]
@Dyanngg Has tackled this in https://github.com/kubernetes/enhancements/pull/3660
