### ISSUE TITLE
Consider changing front-page diagram to explain "priority" a little better

### ISSUE THREAD

**Issue by rahulkjoshi** [kubernetes-sigs/network-policy-api#44]
We might consider changing the image on the website to use "Evaluated first" and "Evaluated Last" instead of a "priority" arrow, which I felt a little confusing. (sorry about the crappy Paint job 😄 )

Current image: [site-src/images/ANP-api-model.png](https://github.com/kubernetes-sigs/network-policy-api/blob/823a0d13a5afc566f19997db6a957de3de92c728/site-src/images/ANP-api-model.png)

**New proposal**

![image](https://user-images.githubusercontent.com/1559605/192350135-c81de551-ecd6-4f13-bce6-7890f227ce59.png)

**Comment by astoycos** [comment]
Thanks @rahulkjoshi I really appreciate the feedback and will change this :)

**Comment by tssurya** [comment]
I did this as part of k8s presentation let me take this and fix it.

**Comment by tssurya** [comment]
(note that I spoke to @bpickard22 offline and he was cool with it.)
