### ISSUE TITLE
[Feature Request] - Ability to Simulate a Network Policy

### ISSUE THREAD

**Issue by cailynse** [kubernetes-sigs/network-policy-api#46]
In an effort to have a secure network many projects will have a set of default k8s network policies deployed. It would be useful to be able to get an idea of how the current traffic would be impacted by a network policy before deploying it. It would be nice to know what traffic will be blocked by a given policy so that we could more confidentially create exceptions, and ensure there will be as little downtime as possible on deployment.

**Comment by mattfenwick** [comment]
hi @cailynse this sounds like exactly what [cyclonus](https://github.com/mattfenwick/cyclonus) was designed for -- cyclonus has a netpol engine which evaluates network policies and can generate expected connectivity matrices, without even needing a kubernetes cluster.

If this is interesting/useful to you, let me know how I can help you !

You could use it either as a `kubectl` plugin or a library.

(note: cyclonus is in the process of adoption by this repo !  see https://github.com/kubernetes-sigs/network-policy-api/tree/master/cmd/cyclonus )

**Comment by cailynse** [comment]
Hi! Amazing! I'm actually planning on attending a cyclonus demo on Monday with SIG-network-policy-api so hopefully that will give me a good primer! Thanks for the help!!
