### ISSUE TITLE
Determine how to best organize APIs 

### ISSUE THREAD

**Issue by astoycos** [kubernetes-sigs/network-policy-api#50]
Currently the object definitions for the AdminNetworkPolicyAPI live in `/apis/v1alpha1` However in the future we'll most likely add more APIs which fall under the
`sig-network-policy-api` umbrella such as networkpolicy V2.... And when those land they will also be in `/apis/v1alpha1`

So this issue just needs to answer: 

Do we need separate directories for each API? i.e (`/apis/admin-network-policy-api/v1alpha1/..` and `/apis/network-policy-v2-api/v1alpha1` etc) 

OR 

Should we really be really be only defining a single API per repo (would result in alot of duplicated code)

**Comment by astoycos** [comment]
@robscott @danwinship Maybe you all have some opinions on this ^^?

**Comment by tssurya** [comment]
> So this issue just needs to answer:
> 
> Do we need separate directories for each API? i.e (`/apis/admin-network-policy-api/v1alpha1/..` and `/apis/network-policy-v2-api/v1alpha1` etc)

IMHO, yes

> 
> OR
> 
> Should we really be really be only defining a single API per repo (would result in alot of duplicated code)

I'd say NO, like the ReadMe suggests which we should probably update with more info, we should aim at hosting all the APIs that we plan to have as part of network-policy-api sig, 

but we can also cross that bridge when we start to host the new APIs.. moving around the code shouldn't be that hard don't see the need to do it now, but in future when we do have more than one we should totally do this.

**Comment by robscott** [comment]
In the upstream k/k repo, types are organized by API Groups (https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/api/networking). So I guess the big question would be what API groups you plan on using for future APIs. In Gateway API we've used a single API group for all our resources so far.

**Comment by astoycos** [comment]
Good point... Currently we're using `policy.networking.k8s.io` which I think is plenty generic for all future policy APIs

The only thing I wasn't sure on is.... do all objects defined in a single API group need to stay consistent regarding versioning? 

For Example.....the AdminNetworkPolicy API Objects (`AdminNetworkPolicy` and `BaselineAdminNetworkPolicy`) progress to v1beta1 and then we make a new API (in the same group) called netpol_v2 API .... Can the objects for that new API be in v1alpha1 while the other objects (ANP + BANP) in the same group are in a different versioning state?

**Comment by robscott** [comment]
That's what we're doing with Gateway API. I think we have a bit more flexibility here since we're using CRDs. With that said, even in upstream, resources within the networking group graduated to v1 at different points.

**Comment by astoycos** [comment]
Cool I just wanted to make sure that was the right way of doing things :) 

We'll keep on it then, thanks @robscott @tssurya for the input!! 

I'll close this as solved, i.e keep doing what we're already doing
