### ISSUE TITLE
Motivate Network Plugins to Use Port Names/DNS 

### ISSUE THREAD

**Issue by cailynse** [kubernetes-sigs/network-policy-api#52]
As per a discussion between SIG-Security and SIG-Network: We want to ensure that CNIs are using named ports so that NetworkPolicy can be used to allow access with DNS.

Our proposed first step is to write an e2e test that checks if a NetworkPolicy allowing egress to the named port 'dns' allows access to DNS regardless of what port the pods are listening on. This would then be followed up with discussion in the SIG-Network meeting and communicated through the mailing list.

**Comment by tssurya** [comment]
ah I realized I already have a card for ANP here: https://github.com/kubernetes-sigs/network-policy-api/issues/100
I will unassign myself from this one which is for network policy in case someone is interested.
