### ISSUE TITLE
Add documentation in the API comments for priority between rules in a single ANP object

### ISSUE THREAD

**Issue by astoycos** [kubernetes-sigs/network-policy-api#56]
In the KEP we specify https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2091-admin-network-policy#priority: 

```
The relative precedence of the rules within a single ANP object (all of which share a priority) will be determined by the order in which the rule is written. Thus, a rule that appears at the top of the ingress/egress rules would take the highest precedence.
```

But I don't _think I_ know this from reading the actual API types :) 

Pretty simple update to the API comments should fix this

**Comment by tssurya** [comment]
thanks.. on it! will submit a PR tomorrow.
