### ISSUE TITLE
set future course for network policy engine + conformance (formerly: Cyclonus)

### ISSUE THREAD

**Issue by mattfenwick** [kubernetes-sigs/network-policy-api#62]
Follow up on https://github.com/kubernetes-sigs/network-policy-api/issues/34 -- what is the future of this network policy tool?

I suggest considering:

 - [ ] rename to something appropriate for kubernetes-sigs (positive side effect: disambiguates from my personal project)
 - [ ] define goals
   - [ ] engine
     - [ ] features
       - [ ] ANP
       - [ ] BANP
     - [ ] applications
       - [ ] understand use cases -- CI, end user, https://github.com/kubernetes-sigs/network-policy-api/issues/46
   - [ ] conformance suite
     - [ ] ANP
     - [ ] BANP
   - [ ] builds, distros, devex
     - [ ] binaries
     - [ ] images
     - [ ] kubectl plugin
     - [ ] yaml for k8s deploys

Note: this is just off the top of my head, I'm sure there are more things to consider.

**Comment by mattfenwick** [comment]
@astoycos feel free to close if this isn't useful, I see problems like: build scripts in this repo point to my personal repos, and want to figure out how I can help the community to tackle them!

**Comment by olivercodes** [comment]
@mattfenwick @astoycos happy to file some issues against this. 

For Build/Distribution related items, would we want to publish to registry.k8s.io? Or just under releases on our repo?

**Comment by astoycos** [comment]
/assign @olivercodes  

thanks that would be great! 

> For Build/Distribution related items, would we want to publish to registry.k8s.io? Or just under releases on our repo?

Let's talk about this in today's meeting

**Comment by olivercodes** [comment]
Confirmed in 12/5 meeting, we'll use GHCR. No binaries for now, may change in future if need/convenience for someone is there.

**Comment by olivercodes** [comment]
@mattfenwick @astoycos 

Engine one created here - https://github.com/kubernetes-sigs/network-policy-api/issues/69

Can probably track "add conformance suite" with the original conformance tests issue? - https://github.com/kubernetes-sigs/network-policy-api/issues/35

### Kubectl Plugin
- I don't think we've really discussed the lifecycle/usage of the kubectl plugin yet (and admittedly I'm not as familiar with it yet, other than what Matt showed me). Probably a good topic for next meeting.

### Rename the tool
- Probably want to decide on that before someone tackles https://github.com/kubernetes-sigs/network-policy-api/issues/68
- Any ideas for name @mattfenwick ?
