### ISSUE TITLE
Multiple link broken

### ISSUE THREAD

**Issue by kundan2707** [kubernetes-sigs/network-policy-api#64]
Multiple link broken in network-policy-api/blob/master/site-src/index.md
- [API overview]
- [Examples]
- get involved

**Comment by astoycos** [comment]
Thanks for Opening an issue @kundan2707! 

Can you clarify the location of these broken links? When I go to https://network-policy-api.sigs.k8s.io/#getting-started all three of the links (Api Overview, Examples, Api Source) seem to work for me

**Comment by kundan2707** [comment]
@astoycos  link were not working in  network-policy-api/blob/master/site-src/index.md but its working in  https://network-policy-api.sigs.k8s.io/#getting-started

Although one link for "get involved" in bottom of page is not working for both location.

**Comment by astoycos** [comment]
I'll pick this up in #59
