### ISSUE TITLE
Extend Cyclonus Engine to support ANP & BANP

### ISSUE THREAD

**Issue by olivercodes** [kubernetes-sigs/network-policy-api#69]
https://github.com/kubernetes-sigs/network-policy-api/issues/35 depends on this one.
Downstream issue of https://github.com/kubernetes-sigs/network-policy-api/issues/62

Currently Cyclonus engine does not support ANP and BANP.

**Comment by astoycos** [comment]
@huntergregory Pretty sure you're working on this now? 

If it's alright with you @olivercodes we can re-assign this one

**Comment by huntergregory** [comment]
/close
The basics are supported. We are working on preparing for the first official release. Enhancements are being tracked in the parent issue #150
