### ISSUE TITLE
Add a Script linter to our CI workflow

### ISSUE THREAD

**Issue by astoycos** [kubernetes-sigs/network-policy-api#94]
We're maintaining a ton of scripts here, it'd be nice to have a shell script specific linter like https://www.shellcheck.net/ or something to make sure we don't miss silly things :)

**Comment by v1ku** [comment]
Hello @astoycos ,

I'm working on integrating ShellCheck into the project as requested in this issue. Before proceeding, I would like to clarify a few points about the CI/CD pipeline.

    Is there an existing CI/CD pipeline for this project that I may have missed? If yes, could you please point me to the relevant configuration files?
    If there isn't a CI/CD pipeline set up, are developers expected to run the ShellCheck script manually before pushing their changes to the repository?

**Comment by astoycos** [comment]
Hi @v1ku, thanks for taking this!! 

There is an existing ci/cd pipeline setup managed with prow, let me point you to a PR that should help guide you here.

I think first thing is adding a make target to our local setup to do so and then actually adding a new step to our test-infra setup.

https://github.com/kubernetes-sigs/network-policy-api/issues/37 _should_ help answer any questions.

Meanwhile feel free to ping me here or on slack for more help.

**Comment by astoycos** [comment]
@v1ku Will you have time to tackle this in the near future? If not please unassign and open up for other contributors 👍
